name: Automated JMeter Tests

on: 
  push:
    branches: 
      - main

jobs:
  automated-jmeter-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JMeter
        run: choco install jmeter -y

      - name: Check JMeter Version
        run: jmeter -v

      - name: Verify JMeter Installation
        run: |
          if (Get-Command jmeter -ErrorAction SilentlyContinue) {
            Write-Host "JMeter is installed."
          } else {
            Write-Host "JMeter is not installed."
            exit 1
          }

      - name: Run JMeter Tests
        run: |
          jmeter -n -t ./Task.jmx -l ./results/result.jtl -e -o ./html
        continue-on-error: true  # Allows the job to run other steps even if this fails

      - name: List Results Directory
        run: |
          echo "Listing results directory:"
          dir results
          dir html

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results/result.jtl

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: html
          if-no-files-found: error
